### ISSUE TITLE
licensing

### ISSUE THREAD

**Issue by awuctl** [MishaTY/WindowsPackageDownloader#4]
I figured I'd ask again, what gives you the right to steal code and relicense it to GPL?

**Comment by MishaTy** [comment]
Where did I steal code? I removed the WuClient class and was going to rewrite it anyways.

**Comment by awuctl** [comment]
must've gone blind from all the C#
have a good one, cheers

**Comment by awuctl** [comment]
my general suggestion is to not bother trying to make uup dump into good code
(impossible, it's been tried many times)
just let us let it die

**Comment by MishaTy** [comment]
I won't, thanks for your suggestion.
